{% set name = "lalpulsar" %}
{% set version = "7.0.1" %}

# dependencies
{% set lal_version = "7.6.0" %}
{% set lalframe_version = "3.0.0" %}
{% set lalinference_version = "4.1.0" %}
{% set lalsimulation_version = "6.0.0" %}
{% set swig_version = "4.2.1" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: cb316bfb485df22f96d2eb92f1178b65c2880e8765f281aa3e01454a3b1f7647

build:
  error_overlinking: true
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - help2man >=1.37  # [build_platform == target_platform]
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - make
    - pkg-config >=0.18.0
    - python >=3.5
    - swig {{ swig_version }}
  host:
    - cfitsio
    - fftw * nompi*
    - gsl
    - liblal >={{ lal_version }}
    - liblalframe >={{ lalframe_version }}
    - liblalinference >={{ lalinference_version }}
    - liblalsimulation >={{ lalsimulation_version }}
    - libgomp  # [linux]
    # extras for `make check` (when not cross-compiling)
    - bc  # [build_platform == target_platform]
    - lalframe >={{ lalframe_version }}  # [build_platform == target_platform]

outputs:
  - name: lalpulsar-data
    script: install-data.sh
    requirements:
      build:
        - make
      run_constrained:
        - liblalpulsar >=4.0.0
    test:
      commands:
        - test -f ${LALPULSAR_DATADIR}/sun00-40-DE405.dat.gz  # [unix]
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalpulsar/
      dev_url: https://git.ligo.org/lscsoft/lalsuite.git
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Pulsar Library data files
      description: |
        The LSC Algorithm Pulsar Library for gravitational wave data analysis.
        This package contains the data files needed to run various applications
        and routines that use the LAL Pulsar library.

  - name: liblalpulsar
    script: install-lib.sh
    build:
      error_overlinking: true
      ignore_run_exports:
        # run_exports parsing for fftw is broken, so we ignore it
        # manually, for now
        - fftw
      run_exports:
        - {{ pin_subpackage("liblalpulsar", max_pin="x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - libgomp  # [linux]
        - llvm-openmp  # [osx]
        - make
        - swig {{ swig_version }}
      host:
        - cfitsio
        - fftw * nompi*
        - gsl
        - {{ pin_subpackage('lalpulsar-data', exact=True) }}
        - liblal >={{ lal_version }}
        - liblalframe >={{ lalframe_version }}
        - liblalinference >={{ lalinference_version }}
        - liblalsimulation >={{ lalsimulation_version }}
        - libgomp  # [linux]
      run:
        - cfitsio
        - fftw
        - gsl
        - {{ pin_subpackage('lalpulsar-data', exact=True) }}
        - liblal >={{ lal_version }}
        - liblalframe >={{ lalframe_version }}
        - liblalinference >={{ lalinference_version }}
        - liblalsimulation >={{ lalsimulation_version }}
      run_constrained:
        - lalpulsar >=3.0.0
        - python-lalpulsar >=3.0.0
    test:
      requires:
        - pkg-config  # [unix]
      commands:
        # check library
        - test -f ${PREFIX}/lib/liblalpulsar${SHLIB_EXT}  # [unix]
        # check pkg-config
        - pkg-config --print-errors --exact-version "${PKG_VERSION}" lalpulsar
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalpulsar/
      dev_url: https://git.ligo.org/lscsoft/lalsuite.git
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Pulsar Library shared object libraries
      description: |
        The LSC Algorithm Pulsar Library for gravitational wave data analysis.
        This package contains the shared-object libraries needed to run
        applications that use the LAL Pulsar library.

  - name: python-lalpulsar
    script: build-python.sh
    build:
      error_overlinking: true
      # no python-lalburst on Python 3.9
      # (astropy (for python-lalsimulation) is incompatible with numpy 2)
      skip: true  # [win or py<310]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - help2man >=1.37  # [py!=39 and build_platform == target_platform]
        - make
        - pkg-config
        - swig {{ swig_version }}
        # extras for cross-compiling:
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy                               # [build_platform != target_platform]
        - python                              # [build_platform != target_platform]
      host:
        - {{ pin_subpackage('liblalpulsar', exact=True) }}
        - numpy
        - python
      run:
        - astropy-base
        - {{ pin_subpackage('liblalpulsar', exact=True) }}
        - numpy
        - python
        - python-lal >={{ lal_version }}
        - python-lalframe >={{ lalframe_version }}
        - python-lalinference >={{ lalinference_version }}
        - python-lalsimulation >={{ lalsimulation_version }}
        - six
    test:
      requires:
        - pytest >=4.0.0a0
      source_files:
        - test/python
        - lib/*.dat.gz
      commands:
        - LAL_TEST_PKGDATADIR="./lib" python -m pytest -ra -v test/python  # [build_platform == target_platform]
      imports:
        - lalpulsar
        - lalpulsar.NstarTools
        - lalpulsar.PulsarParametersWrapper
        - lalpulsar.knope_utils
        - lalpulsar.pulsarhtmlutils
        - lalpulsar.pulsarpputils
        - lalpulsar.simulateCW
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalpulsar/
      dev_url: https://git.ligo.org/lscsoft/lalsuite.git
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Pulsar Library Python libraries
      description: |
        The LSC Algorithm Pulsar Library for gravitational wave data analysis.
        This package contains the Python bindings of the LALPulsar C libraries
        and additional Python modules.

        Note: this package only provides the importable Python libraries.
        All command-line interfaces, scripts, and executables are
        part of the `lalpulsar` package.

  - name: lalpulsar
    script: install-bin.sh
    build:
      # no python-lalburst on Python 3.9
      # (astropy (for python-lalsimulation) is incompatible with numpy 2)
      skip: true  # [win or py<310]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - help2man >=1.37  # [py!=39 and build_platform == target_platform]
        - make
        - sed
      host:
        - cfitsio
        - fftw
        - gsl
        - liblal >={{ lal_version }}
        - liblalframe >={{ lalframe_version }}
        - liblalinference >={{ lalinference_version }}
        - {{ pin_subpackage('liblalpulsar', exact=True) }}
        - liblalsimulation >={{ lalsimulation_version }}
        - numpy
        - python
        # requirements for make check / manual generation
        - astropy-base  # [py!=39 and build_platform == target_platform]
        - bc  # [py!=39 and build_platform == target_platform]
        - h5py  # [py!=39 and build_platform == target_platform]
        - jplephem  # [py!=39 and build_platform == target_platform]
        - lalframe >={{ lalframe_version }}  # [py!=39 and build_platform == target_platform]
        - lalinference >={{ lalinference_version }}  # [py!=39 and build_platform == target_platform]
        - pytest  # [py!=39 and build_platform == target_platform]
        - python-lal >={{ lal_version }}  # [py!=39 and build_platform == target_platform]
        - python-lalframe >={{ lalframe_version }}  # [py!=39 and build_platform == target_platform]
        - python-lalinference >={{ lalinference_version }}  # [py!=39 and build_platform == target_platform]
        - {{ pin_subpackage('python-lalpulsar', exact=True) }}  # [py!=39 and build_platform == target_platform]
        - python-lalsimulation >={{ lalsimulation_version }}  # [py!=39 and build_platform == target_platform]
        - scipy   # [py!=39 and build_platform == target_platform]
      run:
        - astropy-base
        - fftw
        - jplephem
        - liblal >={{ lal_version }}
        - liblalframe >={{ lalframe_version }}
        - liblalsimulation >={{ lalsimulation_version }}
        - liblalinference >={{ lalinference_version }}
        - lalinference >={{ lalinference_version }}
        - {{ pin_subpackage('liblalpulsar', exact=True) }}
        - numpy
        - python
        - python-lal >={{ lal_version }}
        - python-lalframe >={{ lalframe_version }}
        - python-lalinference >={{ lalinference_version }}
        - python-lalsimulation >={{ lalsimulation_version }}
        - {{ pin_subpackage('python-lalpulsar', exact=True) }}
    test:
      commands:
        - lalpulsar_create_time_correction_ephemeris --help
        - lalpulsar_fits_header_getval --help
        - lalpulsar_fits_header_list --help
        - lalpulsar_fits_overview --help
        - lalpulsar_fits_table_list --help
        - lalpulsar_heterodyne --help
        - lalpulsar_knope --help
        - lalpulsar_knope_collate_results --help
        #- lalpulsar_knope_result_page --help  <- needs scotchcorner
        - lalpulsar_frequency_evolution --help
        - lalpulsar_parameter_estimation_nested --help
        - lalpulsar_splitSFTs --help
        - test "$(lalpulsar_ssbtodetector --gps 1000000000 --ra 0 --dec 0 --telescope JBO)" == "999999506.306100250"
        - lalpulsar_version --verbose
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalpulsar/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Pulsar Library
      description: |
        The LSC Algorithm Pulsar Library for gravitational wave data analysis.

about:
  home: https://wiki.ligo.org/Computing/LALSuite
  doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalpulsar/
  dev_url: https://git.ligo.org/lscsoft/lalsuite/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm Pulsar Library
  description: |
    The LSC Algorithm Pulsar Library for gravitational wave data analysis.

extra:
  feedstock-name: lalpulsar
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
