{% set name = "lalpulsar" %}
{% set version = "3.1.1" %}
{% set sha256 = "d0b89ee4508870dff9f0d086f50e3f3a7d218c41af96e6dbea582e90e94f2f21" %}

# dependencies
{% set lal_version = "7.1.0" %}
{% set lalframe_version = "1.5.0" %}
{% set swig_version = "3.0.10" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    # skip gsl_version check when cross compiling
    - no-gsl_version-check.patch  # [build_platform != target_platform]

build:
  error_overdepending: true
  error_overlinking: true
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - help2man >=1.37
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - make
    - pkg-config >=0.18.0
    - swig >={{ swig_version }}
  host:
    - cfitsio
    - fftw * nompi*
    - gsl
    - liblal >={{ lal_version }} fftw*
    - liblalframe >={{ lalframe_version }}
    - libgomp  # [linux]
    - llvm-openmp  # [osx]

outputs:
  - name: liblalpulsar
    script: install-lib.sh
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        # run_exports parsing for fftw is broken, so we ignore it
        # manually, for now
        - fftw
      run_exports:
        - {{ pin_subpackage("liblalpulsar", max_pin="x") }}
    requirements:
      build:
        - {{ compiler('c') }}
        - libgomp  # [linux]
        - llvm-openmp  # [osx]
        - make
        - swig >={{ swig_version }}
      host:
        - cfitsio
        - fftw * nompi*
        - gsl
        - liblal >={{ lal_version }} fftw*
        - liblalframe >={{ lalframe_version }}
        - libgomp  # [linux]
        - llvm-openmp  # [osx]
      run:
        - cfitsio
        - fftw
        - gsl
        - liblal >={{ lal_version }}
        - liblalframe >={{ lalframe_version }}
      run_constrained:
        - lalpulsar >=3.0.0
        - python-lalpulsar >=3.0.0
    test:
      requires:
        - pkg-config  # [unix]
      commands:
        # check library
        - test -f ${PREFIX}/lib/liblalpulsar${SHLIB_EXT}  # [unix]
        # check activate variables
        - test "${LALPULSAR_DATADIR}" = "${PREFIX}/share/lalpulsar"  # [unix]
        # check pkg-config
        - pkg-config --print-errors --exact-version "${PKG_VERSION}" lalpulsar
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalpulsar/
      dev_url: https://git.ligo.org/lscsoft/lalsuite.git
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Pulsar Library shared object libraries
      description: |
        The LSC Algorithm Pulsar Library for gravitational wave data analysis.
        This package contains the shared-object libraries needed to run
        applications that use the LAL Pulsar library.

  - name: python-lalpulsar
    script: install-python.sh
    build:
      error_overdepending: true
      error_overlinking: true
      ignore_run_exports:
        - openssl
        # ignore run_exports from python's recipe
        - python
    requirements:
      build:
        - {{ compiler('c') }}
        - help2man >=1.37
        - make
        - pkg-config
        - swig >={{ swig_version }}
        # extras for cross-compiling:
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy                               # [build_platform != target_platform]
        - python                              # [build_platform != target_platform]
      host:
        - {{ pin_subpackage('liblalpulsar', exact=True) }}
        - numpy
        - openssl
        - python
      run:
        - astropy
        - {{ pin_subpackage('liblalpulsar', exact=True) }}
        - {{ pin_compatible('numpy') }}
        - python
        - python-lal >={{ lal_version }}
        - python-lalframe >={{ lalframe_version }}
        - six
    test:
      requires:
        - pytest >=4.0.0a0
      source_files:
        - test/python
        - lib/*.dat.gz
      commands:
        - LAL_TEST_PKGDATADIR="./lib" python -m pytest -ra -v test/python
      imports:
        - lalpulsar
        - lalpulsar.NstarTools
        - lalpulsar.PulsarParametersWrapper
        - lalpulsar.simulateCW
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalpulsar/
      dev_url: https://git.ligo.org/lscsoft/lalsuite.git
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Pulsar Library Python libraries
      description: |
        The LSC Algorithm Pulsar Library for gravitational wave data analysis.
        This package contains the Python bindings of the LALPulsar C libraries
        and additional Python modules.

        Note: this package only provides the importable Python libraries.
        All command-line interfaces, scripts, and executables are
        part of the `lalpulsar` package.

  - name: lalpulsar
    script: install-bin.sh
    build:
      ignore_run_exports:
        - openssl
        - python
    requirements:
      build:
        - {{ compiler('c') }}
        - help2man >=1.37
        - make
        - sed
      host:
        - liblal >={{ lal_version }}
        - {{ pin_subpackage('liblalpulsar', exact=True) }}
        - openssl
        - python
      run:
        - liblal >={{ lal_version }}
        - {{ pin_subpackage('liblalpulsar', exact=True) }}
        - python
        - {{ pin_subpackage('python-lalpulsar', exact=True) }}
    test:
      commands:
        - lalpulsar_version --verbose
    about:
      home: https://wiki.ligo.org/Computing/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalpulsar/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPL-2.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Pulsar Library
      description: |
        The LSC Algorithm Pulsar Library for gravitational wave data analysis.
        This package contains the shared-object libraries needed to run
        applications that use the LAL Pulsar library.  If you want to install
        the Python bindings, please install the associated python-lalpulsar
        package.

about:
  home: https://wiki.ligo.org/Computing/LALSuite
  doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalpulsar/
  dev_url: https://git.ligo.org/lscsoft/lalsuite/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm Pulsar Library
  description: |
    The LSC Algorithm Pulsar Library for gravitational wave data analysis.

extra:
  feedstock-name: lalpulsar
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
