{% set name = "lalpulsar" %}
{% set version = "1.17.1" %}
{% set sha256 = "e60fee8051d556ad789975df6a1516bd3dee4abb3fcf3552609f80fa011718cb" %}

{% set lal_version = "6.19.2" %}
{% set swig_version = "3.0.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - pkg-config
    - swig >={{ swig_version }}
  host:
    - cfitsio
    - fftw
    - gsl
    - lal >={{ lal_version }}
  run:
    - cfitsio
    - fftw
    - gsl
    - lal >={{ lal_version }}

test:
  commands:
    - lalpulsar_version --verbose

outputs:
  - name: lalpulsar

  - name: python-lalpulsar
    script: install-python.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - pkg-config
        - swig >={{ swig_version }}
      host:
        - {{ pin_subpackage('lalpulsar', exact=True) }}
        - numpy
        - python
        - python-lal >={{ lal_version }}
      run:
        - astropy
        - {{ pin_subpackage('lalpulsar', exact=True) }}
        - {{ pin_compatible('numpy') }}
        - python
        - python-lal >={{ lal_version }}
        - six
    test:
      imports:
        - lalpulsar
        - lalpulsar.NstarTools
        - lalpulsar.PulsarParametersWrapper
        - lalpulsar.simulateCW
    about:
      home: https://wiki.ligo.org/Computing/DASWG/LALSuite
      doc_url: https://docs.ligo.org/lscsoft/lalsuite/lalpulsar/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPLv2+
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Pulsar Library
      description: |
        The LSC Algorithm Pulsar Library for gravitational wave data analysis.
        This package contains the python bindings.

about:
  home: https://wiki.ligo.org/Computing/DASWG/LALSuite
  doc_url: https://docs.ligo.org/lscsoft/lalsuite/lalpulsar/
  dev_url: https://git.ligo.org/lscsoft/lalsuite/
  license: GPLv2+
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm Pulsar Library
  description: |
    The LSC Algorithm Pulsar Library for gravitational wave data analysis.
    This package contains the shared-object libraries needed to run
    applications that use the LAL Pulsar library.  If you want to install
    the Python bindings, please install the associated python-lalpulsar
    package.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
