{% set name = "lalpulsar" %}
{% set version = "1.17.1" %}
{% set sha256 = "e60fee8051d556ad789975df6a1516bd3dee4abb3fcf3552609f80fa011718cb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - make
    - swig >=3.0.7
  host:
    - cfitsio
    - fftw
    - gsl
    - lal >=6.19.0

outputs:
  - name: lalpulsar
    script: install-c.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - pkg-config
        - make
        - swig >=3.0.7
      host:
        - cfitsio
        - fftw
        - gsl
        - lal >=6.19.0
      run:
        - cfitsio
        - fftw
        - gsl
        - lal >=6.19.0
    test:
      commands:
        - lalpulsar_version --verbose
    about:
      home: https://wiki.ligo.org/Computing/DASWG/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalpulsar/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPLv2+
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Pulsar Library
      description: |
        The LSC Algorithm Pulsar Library for gravitational wave data analysis.
        This package contains the shared-object libraries needed to run
        applications that use the LAL Pulsar library.

  - name: python-lalpulsar
    script: install-python.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - pkg-config
        - make
        - swig >=3.0.7
      host:
        - {{ pin_subpackage('lalpulsar', exact=True) }}
        - python
        - numpy
        - python-lal >=6.19.0
      run:
        - {{ pin_subpackage('lalpulsar', exact=True) }}
        - python
        - {{ pin_compatible('numpy') }}
        - python-lal >=6.19.0
        - astropy
    test:
      imports:
        - lalpulsar
        - lalpulsar.NstarTools
        - lalpulsar.PulsarParametersWrapper
        - lalpulsar.simulateCW
    about:
      home: https://wiki.ligo.org/Computing/DASWG/LALSuite
      doc_url: https://lscsoft.docs.ligo.org/lalsuite/lalpulsar/
      dev_url: https://git.ligo.org/lscsoft/lalsuite/
      license: GPLv2+
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Pulsar Library
      description: |
        The LSC Algorithm Pulsar Library for gravitational wave data analysis.
        This package contains the python bindings.

about:
  home: https://wiki.ligo.org/Computing/DASWG/LALSuite
  license: GPLv2+
  license_family: GPL
  summary: LSC Algorithm Pulsar Library

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
