appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: fXXmOGCToXOb26CxvA+DK6Ro7HIlMk7lHNuC4qwZoG/NQOtI39mq8kAF3sl+xgKqGWS8HqKa/+pqN0Vvj8VvFW7LJxm8UVpgFlVUf8nwKibS3vNqvZDMIcNp1mCZhP/D826ibvIdHHm0i+kG7wMH0pfVVmeuCfqQ9KlwdF5vAneog5Z+8S0Tjk8eQgyZ3IGI/EBC/ZIJFY+ajAj8agwxvt7YtkXdEcounilpF/fXek0jranjujv94Sj5TQCWn26Do2WWcFa42bN+DSxbcP7ZVntFbie7cpYUyoIWIUiYdLgI+Oy9UFvhrbtCm8ydDll2v9mbma0awZf/iZhzSMS3JilYZ1QNv7QXYd+ERL0TFe7qO5Eqyw7Pfc6jpoA+dZOuG5aDWxNGd6EQZxckAg7IOxEqY8zxxJeQpFM6avKUA7PKTg6vbkWtT3aNMBGJcM6jODNUvThVlOmGbD31FiWo63RgAcknKmZRXRNew/AVqy4eQVGzXugST2bTWYyHMD2vWK+mX7NzdTOUnVr5Pmmflz4d2NbAOWjrmefcCqrumNrLIHhPD6gF5DZ/6k58863QQkJg/dRsP3AWYkldUJno+bGWdrXAoZeXtFXxKoTqw09ruUMoxIZM8RpHJhh7670fe9jarptwVm3xUwUKlRMRxiFhl/firjxGv9sQDo74Cz8=}
